name = "apex-prime"
main = "worker/index.js"
compatibility_date = "2026-09-22"
compatibility_flags = ["nodejs_compat"]

[vars]
PUBLIC_API_DATABASE = "production"
ADMIN_EMAILS = "admin@theprimemarkets.com"
REGISTRATION_ENABLED = "true"
DEPOSITS_ENABLED = "true"

[assets]
directory = "./dist"
binding = "ASSETS"

[[r2_buckets]]
binding = "KYC_FILES"
bucket_name = "apex-prime-production-kyc"

[[d1_databases]]
binding = "DB"
database_name = "apex-prime-db"
database_id = "b89ee3f0-d30a-42a3-bb73-06c7ccaf633c"
migrations_dir = "d1-migrations"

[[d1_databases]]
binding = "STAGING_DB"
database_name = "apex-prime-staging"
database_id = "8940eeeb-9cd9-40b6-9478-ff0ae4d91e3a"
migrations_dir = "d1-migrations"

[[env.staging.r2_buckets]]
binding = "KYC_FILES"
bucket_name = "apex-prime-staging-kyc"

[env.staging]
name = "apex-prime-staging-worker"

[env.staging.vars]
PUBLIC_API_DATABASE = "staging"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "apex-prime-staging"
database_id = "8940eeeb-9cd9-40b6-9478-ff0ae4d91e3a"
migrations_dir = "d1-migrations"

[[env.staging.d1_databases]]
binding = "STAGING_DB"
database_name = "apex-prime-staging"
database_id = "8940eeeb-9cd9-40b6-9478-ff0ae4d91e3a"
migrations_dir = "d1-migrations"